### ISSUE TITLE
vector-compat doesn't work with 21.1.2 build tools

### ISSUE THREAD

**Issue by ahmedre** [wnafee/vector-compat#5]
steps to repro - update `demo/build.gradle` and change the `buildToolsVersion` to `21.1.2`. compile and run. observe a crash on launch.

```
E/VectorDrawable( 1528): parser error
E/VectorDrawable( 1528): org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<menu_vector> tag requires width > 0
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:400)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.VectorDrawable.inflate(VectorDrawable.java:330)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.VectorDrawable.create(VectorDrawable.java:304)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.inflate(AnimatedVectorDrawable.java:229)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.create(AnimatedVectorDrawable.java:204)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.getDrawable(AnimatedVectorDrawable.java:185)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:44)
E/VectorDrawable( 1528): 	at com.wnafee.vector.MorphButton.<init>(MorphButton.java:79)
E/VectorDrawable( 1528): 	at com.wnafee.vector.MorphButton.<init>(MorphButton.java:58)
E/VectorDrawable( 1528): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/VectorDrawable( 1528): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/VectorDrawable( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/VectorDrawable( 1528): 	at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
E/VectorDrawable( 1528): 	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
E/VectorDrawable( 1528): 	at com.wnafee.vector.compat.demo.MainActivity.onCreate(MainActivity.java:27)
E/VectorDrawable( 1528): 	at android.app.Activity.performCreate(Activity.java:5231)
E/VectorDrawable( 1528): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/VectorDrawable( 1528): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/VectorDrawable( 1528): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/VectorDrawable( 1528): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/VectorDrawable( 1528): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/VectorDrawable( 1528): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VectorDrawable( 1528): 	at android.os.Looper.loop(Looper.java:136)
E/VectorDrawable( 1528): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/VectorDrawable( 1528): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VectorDrawable( 1528): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VectorDrawable( 1528): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/VectorDrawable( 1528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/VectorDrawable( 1528): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 1528): Shutting down VM
W/dalvikvm( 1528): threadid=1: thread exiting with uncaught exception (group=0xa4d82b20)
E/AndroidRuntime( 1528): FATAL EXCEPTION: main
E/AndroidRuntime( 1528): Process: com.wnafee.vector.compat.demo, PID: 1528
E/AndroidRuntime( 1528): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wnafee.vector.compat.demo/com.wnafee.vector.compat.demo.MainActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class com.wnafee.vector.MorphButton
E/AndroidRuntime( 1528): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 1528): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 1528): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 1528): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 1528): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1528): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1528): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 1528): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1528): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1528): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 1528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 1528): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1528): Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.wnafee.vector.MorphButton
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 1528): 	at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
E/AndroidRuntime( 1528): 	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.compat.demo.MainActivity.onCreate(MainActivity.java:27)
E/AndroidRuntime( 1528): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 1528): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1528): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 1528): 	... 11 more
E/AndroidRuntime( 1528): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1528): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 1528): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 1528): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime( 1528): 	... 22 more
E/AndroidRuntime( 1528): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.inflate(AnimatedVectorDrawable.java:229)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.create(AnimatedVectorDrawable.java:204)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.compat.AnimatedVectorDrawable.getDrawable(AnimatedVectorDrawable.java:185)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:44)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.MorphButton.<init>(MorphButton.java:79)
E/AndroidRuntime( 1528): 	at com.wnafee.vector.MorphButton.<init>(MorphButton.java:58)
E/AndroidRuntime( 1528): 	... 25 more
W/ActivityManager(  511):   Force finishing activity com.wnafee.vector.compat.demo/.MainActivity
```

upgrading to a newer build tools (`22.0.1`, for example) fixes this problem. filing this ticket for two reasons:
1. to serve as a warning if anyone else runs into this problem
2. to investigate and see whether this is broken due to a bug in the build tools (if so, the action item should just be to clearly document it so others don't run into it), or if it's something else.

**Comment by wnafee** [comment]
I found this google issue that explains what's going on on build tools 21.x.x : https://code.google.com/p/android/issues/detail?id=100910

For some reason when AAPT compiles, it splits the drawable xml into a different folder for v21 and "others". In doing so it strips some attributes in the pre-v21 version resulting in the drawable not being inflated properly (in the example mentioned in the issue, `viewportWidth` and `fillColor` are randomly removed but others are kept fine).  

This theoretically means that pre-lollipop devices will see the problem. As part of reproduction of the issue, can you confirm the device/emulator you're using is pre-lollipop?

Others were having the same problem and have suggested is to put the local attributes `app:` before the `android:` ones. Not exactly sure why this works, but it does apparently. It also seems they fixed this problem in build tools 22+.

Should I just update the documentation requiring build tools 22+ or do I add that as a caveat? Do you know of reasons why developers would not be able to simply upgrade to 22?

**Comment by ahmedre** [comment]
yup, this was on KitKat.

**Comment by zawadz88** [comment]
For me splitting the drawables into two folders (drawable and drawable-v21) worked. In v21 I kept android: attributes only and in the other one just app: attributes
